export const FETCH_COURSELIST = 'FETCH_COURSELIST'
export const ADD_COURSE = "ADD_COURSE"
export const ADD_CUSTOM_COURSE = "ADD_CUSTOM_COURSE"
export const REMOVE_COURSE = "REMOVE_COURSE"
export const TOGGLE_COURSE_TERM = "TOGGLE_COURSE_TERM"
export const ADD_TEMP = "ADD_TEMP"
export const REMOVE_TEMP = "REMOVE_TEMP"
export const FILTER_WAITING_LIST = "FILTER_WAITING_LIST"
export const TOGGLE_INSTRUCTION_WRAP = "TOGGLE_INSTRUCTION_WRAP"
export const TOGGLE_COURSE = "TOGGLE_COURSE"


export const JUMP_TO = "JUMP_TO"
export const TOGGLE_TERM = "TOGGLE_TERM"
export const UPDATE_BREAKS = "UPDATE_BREAKS"

export const TOGGLE_LOCK = "TOGGLE_LOCK"

export const SAVE_SCHEDULE = "SAVE_SCHEDULE"
export const LOAD_SCHEDULE = "LOAD_SCHEDULE"
export const REMOVE_SAVE = "REMOVE_SAVE"
export const RESTORE_SAVES_FROM_LOCAL_STORAGE = "RESTORE_SAVES_FROM_LOCAL_STORAGE"